#!/bin/bash

declare -A GOLD_WER

GOLD_WER=( 
  ["iv_en-US"]="17.0" 
  ["iv_en-GB"]="14.52" 
  ["iv_en-AU"]="33.0" 
  ["iv_en-ZA"]="28.4" 
  ["iv_en-GL"]="22.9" 
  ["iv_de-DE"]="42.4" 
  ["iv_de-CH"]="39.7" 
  ["iv_nl-NL"]="46.8" 
  ["iv_nl-BE"]="43.0" 
  ["iv_es-ES"]="37.4" 
  ["iv_es-MX"]="44.0" 
  ["iv_bt-BR"]="32.8" 
  ["iv_fr-FR"]="35.9" 
  ["iv_da-DK"]="58.2" 
  ["iv_nb-NO"]="46.0" 
  ["iv_ca-ES"]="41.4" 
  ["iv_cmn-CH"]="137.0" 
  ["iv_cmn-TW"]="74.0" 
  ["iv_ko-KR"]="96.0" 
  ["iv_ja-JP"]="1013.0" 
  ["iv_ru-RU"]="31.8" 
  ["iv_tl-PH"]="24.0" 
)

